### ISSUE TITLE
Is this a scam repo ?

### ISSUE THREAD

**Issue by jean-emmanuel** [plapier/domflags-extension#12]
![screenshot-2019-04-18-19:57:44](https://user-images.githubusercontent.com/5261671/56381143-4c457880-6214-11e9-836c-a8b7fce9e9c2.png)

**Comment by jean-emmanuel** [comment]
Since 13449d9d851748bb37622fe545070f2cf525b002 it is...

**Comment by plapier** [comment]
Strange. I had a data leak a while back. I've rolled the repo back. Thanks for flagging.

**Comment by jean-emmanuel** [comment]
No problem :)
